socialnetwork/accounts/urls.py
from django.urls import path, include
from . import views
app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

socialnetwork/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('postDetail/<int:pk>', views.PostDetailView.as_view(), name='postDetail'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile'),
]

socialnetwork/socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialnetwork/accounts/models.py
from django.db import models

# Create your models here.

socialnetwork/home/models.py
from datetime import timezone

from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    author = models.CharField(max_length=100)
    picture = models.ImageField(upload_to="posts/%Y/%m/%d")
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

socialnetwork/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class CustomLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

socialnetwork/accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import UserRegisterForm, CustomLoginForm
from django.contrib.auth.mixins import LoginRequiredMixin


class RegisterView(View):
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(username=cd['username'], email=cd['email'], password=cd['password'])
            messages.success(request, 'Account created successfully', 'success')
            return redirect("home:home")

        messages.error(request, 'Something went wrong', 'danger')
        return render(request, self.template_name, {'form': form})


class LoginView(View):
    form_class = CustomLoginForm
    template_name = 'accounts/login.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'You are now logged in', 'success')
                return redirect("home:home")
            else:
                messages.error(request, 'username or password is wrong !!!', 'danger')
                return redirect("accounts:login")

class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, 'You are now logged out', 'success')
        return redirect("home:home")

socialnetwork/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from home.models import Post
from django.contrib.auth.models import User


# Create your views here.

class HomeView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'home/home.html', {'posts': posts})

class PostDetailView(View):
    template_name = 'home/postDetail.html'
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        return render(request, self.template_name, {'post': post} )


class ProfileView(View):
    def get(self, request, user_id):
        user = User.objects.get(pk=user_id)
        userPosts = Post.objects.filter(author=user.username)
        return render(request, 'home/profileView.html', {'user': user, 'userPosts': userPosts})

socialnetwork/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <form method="post" action="" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input value="Login" type="submit" class="btn btn-primary">
    </form>

{% endblock %}

socialnetwork/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register" class="btn btn-primary">
    </form>
{% endblock %}

socialnetwork/home/templates/home/home.html
{% extends 'base.html' %}


{% block content %}

{% endblock %}

socialnetwork/home/templates/home/postDetail.html
{% extends 'base.html' %}

{% block content %}
    <center>
    <h2>{{ post.author }} : </h2><h1>{{ post.title }}</h1><br/>
    <img src="{{ post.picture.url }}"><br/><br/>
    <h3>{{ post.content }}</h3>
    <p>{{ post.date_posted }}</p>
    </center>
{% endblock %}

socialnetwork/home/templates/home/profileView.html
{% extends 'base.html' %}


{% block content %}
    <center>
        <h1>Profile Page</h1><br/>
        <h2>{{ user.username }}</h2><br/>
        {% if userPosts %}
            {% for post in userPosts %}
                <div class="card" style="display: inline-block; width: 18rem; height: 18rem;" >
                    <img src="{{ post.picture.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p>{{ post.date_posted }}</p>
                        <a href={% url "home:postDetail" post.id %}>Read More</a>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </center>
{% endblock %}

socialnetwork/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SocialNetwork</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <ul>
            <li><a href={% url 'home:home' %}>Home</a></li>
            {% if request.user.is_authenticated %}
                <li><a href={% url 'accounts:logout' %}>Logout</a></li>
                <li><a href={% url 'home:profile' request.user.id%}>Profile</a></li>
            {% else %}
                <li><a href={% url 'accounts:register' %}>Register</a></li>
                <li><a href={% url 'accounts:login' %}>Login</a></li>
            {% endif %}
        </ul>
    </nav>
    
    <div class="bodySite" style="padding: 20px;">
        <!-- Message Box -->
        {% if messages %}
            <div class="message-box">
                {% for msg in messages %}
                    <h2>{{ msg }}</h2>
                {% endfor %}
            </div>
        {% endif %}
        <div style="padding: 30px">
            {% block content %}{% endblock %}
        </div>
        <center>
            {% if posts %}
                {% for post in posts %}
                    <div class="card" style="display: inline-block; width: 18rem; height: 18rem" >
                        <img src="{{ post.picture.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p>{{ post.date_posted }}</p>
                            <a href={% url "home:postDetail" post.id %}>Read More</a>
                        </div>
                    </div>
                 {% endfor %}
            {% endif %}
        </center>
    </div>

</body>
</html>